### ISSUE TITLE
If you are using lambda you don't need to pass AWS IAM credentials

### ISSUE THREAD

**Issue by limed** [rtucker-mozilla/nubis-bastionsshkey#24]
If you are using a lambda function we shouldnt need to pass credentials to any IAM operations since this is all allowed via an IAM role

**Comment by rtucker-mozilla** [comment]
@limed After testing, please update and close this out if this issue is resolved.
Thanks!

**Comment by rtucker-mozilla** [comment]
Everything here looks good here. Going to close this out, but we can reopen if necessary.
