### ISSUE TITLE
Ability to create roles

### ISSUE THREAD

**Issue by limed** [rtucker-mozilla/nubis-bastionsshkey#27]
We need to be able to create roles, I propose in the config under the IAMGrouping section we have 1 addtional option, called "privilege" and it can only accept "admin" or "readonly". Based on these values we can decide what sort of policy to provide with the user.

When a user gets created it will create a IAM role with the same name and based on "admin" or "readonly" the IAM role will then get a particular IAM policy attached to it.  I started a little bit of this which might help this process along and I'm working on it on this feature branch: https://github.com/limed/nubis-bastionsshkey/tree/roles

**Comment by limed** [comment]
Comparison of the trees: https://github.com/rtucker-mozilla/nubis-bastionsshkey/compare/master...limed:roles?expand=1

**Comment by rtucker-mozilla** [comment]
Can't we look at the existing IAMPath inside of IAMGroupMapping and then set it to the proper role?

If IAMPath == "/nubis/admin/" then set the role to admin?

**Comment by limed** [comment]
Yeah actually that would work as well

**Comment by rtucker-mozilla** [comment]
This looks all good to go. Closing, but we can reopen if necessary.
