### ISSUE TITLE
Weird issues with execType=consul

### ISSUE THREAD

**Issue by limed** [rtucker-mozilla/nubis-bastionsshkey#9]
I'm seeing some weird issues with execType=consul, note that in my config i'm running with 2 different ldap groups. The `GlobalAdmins` group has a different group than `SudoUsers`

Command ran:
```
$ ./nubis-bastionsshkey -execType=consul
```

Steps to reproduce:

1. Clear our you consul KV store under `/nubis-users`

2. Create `/nubis-users` followed by `/nubis-users/global-admins/` followed by `/nubis-users/sudo-users`

3. Run script ` ./nubis-bastionsshkey -execType=consul`

4. Once you run the script and looked at the KV store what you get is just an empty `/nubis-users` folder

5. Once you run the script again it actually creates the `/nubis-users/global-admins/<users>` and `/nubis-users/sudo-users/<users>` folder however both the KV stores have the same users eventhough I have 2 different groups,  it appears to be only taking the first group

Expected Outcome:
We shouldn't be wiping `/nubis-users/globa-admins` and /nubis-users/sudo-users`  if its pre-created we should just use whats there. And the actual ldap users should be placed in the proper KV store if ran

**Comment by rtucker-mozilla** [comment]
Confirmed this as resolved.
